name: Solution - Build, Test
description: Builds and tests the solution

runs:
  using: composite
  steps:
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Dotnet Restore
      shell: bash
      run: dotnet restore

    - name: Dotnet Build
      shell: bash
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      shell: bash
      run: dotnet test --nologo --verbosity normal
