version: '3'

networks:
  netapitemplate-network:
    driver: bridge

services:
  netapitemplate-service:
    build:
      context: .
      dockerfile: ./src/Service/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - netapitemplate-network
